package com.moutamid.trivialapp;

public class Constants {
    public static final String LICENSE_KEY = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtgT78B8138ga7zci8ObswGa7NhDrtXDT3kOKl6jr7sVYfUL3e1qWyjs5EYL35iCyWad614Grof60qRpaBpeQKOYThhvP5qyNp52okuwJKYRLOR6DJq+7fzYe+GlYiVm08unQSizodGFipqVH1MToPGmYbKjhQcnJNlFSBStMFbL34drqD5KnDO1bMTpILcpCsagK8Z65hQajkGguLe0vho3xfqiOcC7etM3bdRgEZghRMvImRql1o4JxgeGdBuGKP3NRHq8vssX3DrQlqDMioq0EBsK6voVfAuVHjBUkdx60qKGb+doyt+HAoyh1qW/1m3sOjkbmpL6bSwvni9JstQIDAQAB";
    public static final String HUNDRED_DOLLAR_PRODUCT = "hundred.com.moutamid.trivialapp";
}
